replicaCount: 1
image:
  registry: ghcr.io
  repository: galinko87/kbot
  tag: v1.3.0-f30d782
  os: linux
  arch: amd64
  parameters: go
# Define the service section including the port for connectivity tests

secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN
